// AUTO-GENERATED by scripts/wiki-generate.mjs from wiki.config.yaml - do not hand-edit.
// Every value here is a literal copied from wiki.config.yaml - never LLM-generated.

export const wikiConfig = {
  "title": "BusyBuddy Docs",
  "description": "Public documentation and API reference for BusyBuddy.",
  "theme": {
    "accent": "#5169DD",
    "accentHover": "#4257c4",
    "accentMuted": "rgba(81, 105, 221, 0.1)"
  },
  "favicon": "/favicon.svg",
  "githubUrl": "https://github.com/11thandOrange/BusyBuddy_v2",
  "proxyBaseUrl": "https://busybuddy-wiki-backend.example.com",
  "targetApiBaseUrl": "https://your-store.myshopify.com"
} as const;
