// AUTO-GENERATED by scripts/wiki-generate.mjs - do not hand-edit.
// Source of truth is the adjacent .generated.json sidecar, which IS safe
// (and expected) to be hand-edited between generator runs - the merge
// logic in scripts/wiki-extractors/merge.mjs never overwrites or removes
// entries whose extracted source content has not changed.

import type { AppDoc } from '../types';
import data from './apps.generated.json';

export const apps = data as unknown as AppDoc[];

export function getApp(slug: string) {
  return apps.find((a) => a.slug === slug);
}
